env:
  global:
  - REPO_DIR=REmatch
  - BUILD_COMMIT=1486896
  - BUILD_DEPENDS=""
  - MB_ML_VER=2014
  - secure: gDG+60MnqdXNd57tJwmQRcMxjy8bvV62GHdHlOCsPwMJZUEqn9pqV1RpuYHqeMui3HLeCl52UZBV3vjyLdShB7M1JUfTLJSfksKUSnxYlKWciIPQlbiBbPlWM0/gVsYtDvMz7x/F/1S2k6QdpFH7klUmIk7MOFwR+tyGuugRuuse73FNm51IUYBk9SQeC5PByhaF7KBfmADgVILnmHRmzu2NQj97MnJ3jg2e3day8B1FLc9Wc8upxAjmZgzCDcHCbq+iCuPrA0gL3NCA6Otsdn+n9fhRwrqSn5Nrowyy08NCIFkXUktjgm9LUV8zBmMewfm95tlF8WbHAandglu2BuVN14oCewFxqQvx7iXwJRsJ/2NE/trgNAyAHmVQWgmyrUgJgjgC6APTViWl1y9R7lfYZyTR5bT/6SqSY6G4cvqBsFnig/J819HlY21s+xoTcPkKLVzVhDyTF+JhJn6c4YFN3TFK0kiQUinXXGpAhol5xaIjW2T708VWZxQiwd0yMOWulW7dV564fBwuyylk6D9hzsaKFEDepLLq450WaETT7XQGXe7S8V0q2GiCgk4zfApwjih6fFt4WmwARcGNr0LjIf+NeXtn2Gq5Dus+g74WAYrtlCXaLbFW2lGvMR/hYWatYzIJdGN2Vm7BYS8/KT5K7iwgfLSFBHlhMHcoJPg=
  - secure: pm282at/a4cCQxPRVYPr31HD3mrughwVhbmohYc+v04FRNbKMa6ekMUeU4tjm9nQiESc6Srnd3ekuQiXhGYVKMYRq0PnSNpwECVQ95wo0jKLscvdZMBDDCYUlDM9NoFk1VV8RFzaDQ2NGOKpyukQN7iutJAYDMA3AayNKeuvwrYC8K3H1zh9JjOecGkVP2hdcVc08k4CL3vKgGJW+8ltzXAv/9N/0VdyTbKLlHkRYkxBqKU+3/Ak07YAEA5iD1MnAZyU+AwdvJTCYhy/KNDOFRxez0RhL8znDkblaZhOWde2Fr0lYQfF6ir1JeKOMKMINrukXI9rgR+SUevzG2veieCM8j1XVuBiNhTNv1Mgd7f++LB2DHm3kJDrLYX+kNnuF/3uZiM8TaDoa8UUeLuHyEvf0CofFbeAcmuOptbX0WrwVwgq4vsRqxv46scc+BiBi2K6etVVxA7TS3NNClj01rnNXVKH8AQUkmS7owIf9Du6J/oqJJGrpzcKKj3v05Zt12R9Hn/QOC9NNTUk4s8vlRlT9sPIJraX58N3HvICqo5X/e15WIr1NdHuKrjgg1X0oFN5wjttG804vCPV1YVceZy+vfXtB+niSTLNFSHzRZY8laYA398V4hYnfnoxF6+VUe1oXFo5YzLsLq22Oin3sX9UgWDwiLVuNuA+wVjDn74=


language: generic
services: docker
dist: xenial

notifications:
  email: false

matrix:
  include:
  # - os: linux
  #   env:
  #   - MB_PYTHON_VERSION=3.5
  # - os: linux
  #   env:
  #   - MB_PYTHON_VERSION=3.5
  #   - PLAT=i686
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.6
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.6
    - PLAT=i686
  # - os: osx
  #   env:
  #   - MB_PYTHON_VERSION=3.5
  - os: osx
    env:
    - MB_PYTHON_VERSION=3.6
  # - os: osx
  #   env:
  #   - MB_PYTHON_VERSION=3.7
  #   - MB_PYTHON_OSX_VER=10.6
  - os: osx
    env:
    - MB_PYTHON_VERSION=3.7
  - os: osx
    env:
    - MB_PYTHON_VERSION=3.8
  - os: osx
    env:
    - MB_PYTHON_VERSION=3.9


before_install:
- source multibuild/common_utils.sh
- source multibuild/travis_steps.sh
- before_install
install:
- clean_code $REPO_DIR $BUILD_COMMIT
- build_wheel $REPO_DIR $PLAT
script:
- install_run $PLAT

deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh
    on:
      branch: main
