name: pypi-wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest]

    steps:
      - uses: actions/checkout@v2
      - name: "Checkout submodules"
        run: git submodule update --init --recursive

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: 3.8

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==1.7.0

      - name: Build wheels
        env:
          CIBW_BEFORE_ALL_MACOS: "bash scripts/pre_install_macos.sh"
          CIBW_BEFORE_ALL_LINUX: "bash scripts/pre_install_linux.sh"
          CIBW_BUILD: >
            cp36-macosx_x86_64 cp37-macosx_x86_64 cp38-macosx_x86_64
             cp39-macosx_x86_64
             cp36-manylinux_x86_64 cp37-manylinux_x86_64 cp38-manylinux_x86_64
             cp39-manylinux_x86_64
             cp36-manylinux_i686 cp37-manylinux_i686 cp38-manylinux_i686
             cp39-manylinux_i686

        run: |
          python -m cibuildwheel --output-dir wheelhouse REmatch