name: pypi-wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install cibuildwheel
        run: |
          cd REmatch
          python -m pip install cibuildwheel==1.7.0

      - name: Build wheels
        env:
          CIBW_BEFORE_BUILD_MACOS: "scripts/pre_install_macos.sh"
          CIBW_BEFORE_BUILD_LINUX: "scripts/pre_install_linux.sh"

        run: |
          python -m cibuildwheel --output-dir wheelhouse